app:
  name: brain-test
  environment: dev
  region: us-east-1

infrastructure:
  vpc_id: vpc-0efe480ab7051b401
  subnet_id: subnet-0816bd7998fc3436b

ec2:
  instance_type: t3.micro
  os: windows-2022