workload:
  type: k8s-workers
  version: v1

terraform:
  backend:
    bucket: "brainctl-terraform-state"
    key_prefix: "brainctl"
    region: "us-east-1"
    use_lockfile: true

app:
  name: brain-k8s-lab
  environment: prod
  region: us-east-1

infrastructure:
  vpc_id: vpc-xxxxxxxx
  subnet_id: subnet-xxxxxxxx

k8s:
  control_plane_instance_type: t3.large
  worker_instance_type: t3.large
  worker_count: 2
  kubernetes_version: "1.30"
  pod_cidr: "10.244.0.0/16"
  key_name: "" # opcional: informe um key pair existente para acesso SSH
  admin_cidr: "10.0.0.0/24"
  enable_nat_gateway: true
  public_subnet_id: "" # opcional: subnet pública existente para NAT; vazio => cria subnet pública
  public_subnet_cidr: "10.0.254.0/24" # usado apenas quando public_subnet_id estiver vazio
  internet_gateway_id: "" # opcional: internet gateway existente; vazio => detecta IGW da VPC
  private_route_table_id: "" # opcional: route table privada existente; vazio => cria e associa ao subnet_id
  enable_ssm: true
  enable_ssm_vpc_endpoints: true
  enable_detailed_monitoring: true
