workload:
  type: k8s-workers
  version: v1

app:
  name: brain-k8s-lab
  environment: prod
  region: us-east-1

infrastructure:
  vpc_id: vpc-xxxxxxxx
  subnet_id: subnet-xxxxxxxx

k8s:
  control_plane_instance_type: t3.large
  worker_instance_type: t3.large
  worker_count: 2
  kubernetes_version: "1.30"
  pod_cidr: "10.244.0.0/16"
  key_name: "my-ec2-keypair"
  admin_cidr: "10.0.0.0/24"
  enable_ssm: true
  enable_detailed_monitoring: true
