app:
  name: brain-test
  environment: dev
  region: us-east-1

infrastructure:
  vpc_id: vpc-0efe480ab7051b401
  subnet_id: subnet-0816bd7998fc3436b
  subnet_ids:
    - subnet-0816bd7998fc3436b
    - subnet-054b5772b4e01ad14

ec2:
  instance_type: t3.micro
  os: windows-2022
  ami: ""
  user_data_mode: merge
  user_data: |
    <powershell>
      $ErrorActionPreference = "Stop"
      Install-WindowsFeature -Name Web-Server -IncludeManagementTools
      New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot" | Out-Null
      @"
    <html>
      <body>
        <h1>hello world from brainctl</h1>
      </body>
    </html>
    "@ | Set-Content -Path "C:\inetpub\wwwroot\index.html" -Encoding UTF8
      Restart-Service W3SVC
    </powershell>
  imds_v2_required: true

db:
  enabled: true
  instance_type: t3.micro
  port: 1433
  ami: ""
  user_data_mode: default
  user_data: ""

lb:
  enabled: true
  scheme: public
  subnet_ids:
    - subnet-0816bd7998fc3436b
    - subnet-054b5772b4e01ad14
  listener_port: 80
  target_port: 80
  allowed_cidr: 0.0.0.0/0

app_scaling:
  enabled: true
  subnet_ids:
    - subnet-0816bd7998fc3436b
    - subnet-054b5772b4e01ad14
  min_size: 2
  max_size: 4
  desired_capacity: 2
  cpu_target: 60

observability:
  enabled: true
  cpu_high_threshold: 80
  alert_email: "augustt.fabio@gmail.com"


recovery:
  enabled: true
  snapshot_time_utc: "03:00"
  retention_days: 7
  backup_app: true
  backup_db: true
  enable_runbooks: true