workload:
  type: k8s-workers
  version: v1

app:
  name: brain-k8s-lab
  environment: dev
  region: us-east-1

infrastructure:
  vpc_id: vpc-06de730431bfb7107
  subnet_id: subnet-0ad9bdbfb62dcfcca

k8s:
  control_plane_instance_type: t3.medium
  worker_instance_type: t3.medium
  worker_count: 2
  kubernetes_version: "1.30"
  pod_cidr: "10.244.0.0/16"
  key_name: "" # opcional: informe um key pair existente para acesso SSH
  admin_cidr: "0.0.0.0/0"
  enable_nat_gateway: true
  public_subnet_id: "" # opcional: subnet pública existente para NAT; vazio => cria subnet pública
  public_subnet_cidr: "10.0.254.0/24" # usado apenas quando public_subnet_id estiver vazio
  internet_gateway_id: "" # opcional: internet gateway existente; vazio => detecta IGW da VPC
  enable_ssm: true
  enable_ssm_vpc_endpoints: true
  enable_detailed_monitoring: false
