workload:
  type: ec2-app
  version: v1

terraform:
  backend:
    bucket: "pydavi-terraform-state"
    key_prefix: "brainctl"
    region: "us-east-1"
    use_lockfile: true

app:
  name: brain-teste-2
  environment: dev
  region: us-east-1

infrastructure:
  vpc_id: vpc-06de730431bfb7107
  subnet_id: subnet-0ad9bdbfb62dcfcca
  subnet_ids:
    - subnet-0ad9bdbfb62dcfcca
    - subnet-0075a8b0df99ca7c5

ec2:
  instance_type: t3.micro
  os: windows-2022
  ami: "ami-0fc40e7f26d89dac6"
  user_data_mode: merge
  user_data: file://scripts/app-user-data.ps1
  imds_v2_required: true

db:
  enabled: true
  mode: ec2 # ec2 | rds
  instance_type: t3.micro
  port: 1433
  ami: "ami-0fc40e7f26d89dac6"
  user_data_mode: default
  user_data: ""
  # rds:
  #   instance_class: db.t3.micro
  #   engine: postgres
  #   engine_version: "16.3"
  #   allocated_storage: 20
  #   storage_type: gp3
  #   multi_az: false
  #   db_name: appdb
  #   username: brainctl
  #   password: "troque-esta-senha"
  #   backup_retention_days: 7
  #   publicly_accessible: false

lb:
  enabled: true
  scheme: public
  subnet_ids:
    - subnet-0ad9bdbfb62dcfcca
    - subnet-0075a8b0df99ca7c5
  listener_port: 80
  target_port: 80
  allowed_cidr: 0.0.0.0/0
  instance_count: 1

app_scaling:
  enabled: false
  subnet_ids:
    - subnet-0ad9bdbfb62dcfcca
    - subnet-0075a8b0df99ca7c5
  min_size: 2
  max_size: 4
  desired_capacity: 2
  cpu_target: 60

observability:
  enabled: true
  enable_ssm_endpoints: true
  enable_ssm_private_dns: true
  cpu_high_threshold: 80
  alert_email: "augustt.fabio@gmail.com"


recovery:
  enabled: true
  snapshot_time_utc: "03:21"
  retention_days: 7
  backup_app: true
  backup_db: true
  enable_runbooks: true
  drill:
    enabled: true
    schedule_expression: "cron(0 3 1 * ? *)"
    register_to_target_group: false
